### ISSUE TITLE
Processing output 

### ISSUE THREAD

**Issue by protolyser** [felixfischer/node-red-contrib-fritzbox-presence#1]
Hi,
how do I correctly process the output of the node to check if a client is in the network or not (detect if I'm at home with my smartphone).

I tried it with a function node and:
`return msg = false;
var jsonData = JSON.parse(msg.payload);
for (var i = 0; i < jsonData.length; i++) {
    var names = jsonData[i];
     if (names.name == "Phone"){
         {
             msg.payload = true;
             return msg;
         }
    }
}`

But this doesn't detect if it's not there anymore.
Do you have an example of how to use it correctly?

**Comment by felixfischer** [comment]
Hi there,

this flow works for me and outputs an array of objects, each containing a `mac` and `name` field for every active device:

```
[
    {
        "id": "9b89ed50.a4601",
        "type": "tab",
        "label": "Flow 2"
    },
    {
        "id": "a189b5d7.73f498",
        "type": "fritzbox-presence",
        "z": "9b89ed50.a4601",
        "name": "",
        "host": "fritz.box",
        "x": 390,
        "y": 220,
        "wires": [
            [
                "ce56fe81.70f58"
            ]
        ]
    },
    {
        "id": "327b13a0.23ea1c",
        "type": "inject",
        "z": "9b89ed50.a4601",
        "name": "",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "300",
        "crontab": "",
        "once": true,
        "x": 210,
        "y": 220,
        "wires": [
            [
                "a189b5d7.73f498"
            ]
        ]
    },
    {
        "id": "ce56fe81.70f58",
        "type": "function",
        "z": "9b89ed50.a4601",
        "name": "formatting",
        "func": "var data = msg.payload\nvar devs = []\n\ndata.forEach(function(cur) {\n    var i = {\n        mac: cur.mac,\n        name: cur.name\n    }\n    devs.push(i)\n})\n\nmsg.payload = devs\nreturn msg",
        "outputs": 1,
        "noerr": 0,
        "x": 590,
        "y": 220,
        "wires": [
            [
                "feef99c8.5e23a8"
            ]
        ]
    },
    {
        "id": "feef99c8.5e23a8",
        "type": "debug",
        "z": "9b89ed50.a4601",
        "name": "",
        "active": true,
        "console": "false",
        "complete": "false",
        "x": 770,
        "y": 220,
        "wires": []
    }
]
```

Make sure to enter your password in the Fritz!Box node. For my setup, I had to leave the username field blank, as I only login with a password. Also, you will need Fritz!OS >= 5.50 for this to work.

Hope that helps.

**Comment by protolyser** [comment]
Thanks for the example. Does this really work for detecting if someone is home (wifi connection with phone or not)?
With my fritzbox your example lists the "known devices" and that doesn't change when I turn on/off wifi on my phone.
What changes is for example:

```
"summarypropertie":"", --> Offline
"summarypropertie":"2,4 GHz, 144 / 144 Mbit/s", --> Online
```

**Comment by felixfischer** [comment]
I can only test this on my own Fritz!Box 7490 running firmware version 6.60, but it works fairly well for me. Sometimes I cannot see a phone online, which may be because of some kind of sleep mode they go into after some time.

Anyway, you should see the same list of connected devices as in your Fritz!Box interface. If you see a device there which is not listed by my node, please tell me and I'll investigate further.
