### ISSUE TITLE
Node-Red crashes when other DNS service than Fritz!Box' DNS is used

### ISSUE THREAD

**Issue by mjunghanns** [felixfischer/node-red-contrib-fritzbox-presence#2]
Hello Felix,
I noticed an issue that is causing Node-Red to crash. I am using a Fritz!Box 7490, yet I am not using it's build-in DNS resolver but a Bind DNS that is located on a Raspberry PI on the same network segment. I am also not using the *.box namespace, neither am I using the default Fritz!Box IP range.

For this reason my Fritz!Box is not reachable by "fritz.box". Usually, I am accessing it via it's IP address. I tried to configure the node with the box' IP address but it is still trying to resolve "fritz.box" (which seems to be, according to fritz.js,  the default host name). For some reason it seems to ignore the user-configured hostname.

Besides kindly asking you to consider fixing this issue, I would recommend a different approach in dealing with default values. Eversince ICANN did assign the .box - TLD, public DNS requests for fritz.box are resolving to 127.0.53.53. So for people like me, it is double-trouble. If you would define 192.168.178.1 as the default address, if hostname not given by the user, chances would be good that at least the users, operating the box at the default IP address, would have the node able to reach the device. Users, who not only use a different nameserver, but who also use a different IP range would benefit from the node being able to properly handle the user defined host data.

Best regards,
Mark

**Comment by felixfischer** [comment]
Hi Mark,

thank you for the input. I agree that this would be a sensible improvement. Also, the whole .box TLD problem is bothering me as well.

Since I have moved away from Node-Red (to Home Assistant) some while ago, I am not really maintaining this project anymore. But I will see what I can do.

Btw, I've heard that every Fritz!Box can also be reached at 169.254.1.1, no matter what your subnet definition is. This definitely works for me. Does it work for you, too? If so, do you agree that this would be a more general solution than using 192.168.178.1?

Kind regards,
Felix

**Comment by felixfischer** [comment]
I have just replaced fritz.box with 169.254.1.1 in the [dev branch](https://github.com/felixfischer/node-red-contrib-fritzbox-presence/tree/dev). Alas, there is no way for me to quickly verify that this is a sufficient solution. Could you check if it works?

**Comment by oliverlorenz** [comment]
I think #3 could solve that problem.

> Since I have moved away from Node-Red (to Home Assistant) some while ago, I am not really maintaining this project anymore. But I will see what I can do.

If you're interested: I would love to take over that project

**Comment by madnat** [comment]
Hi 169.254.1.1 works for my Fritzbox 7490 also - I did not know that... thanks.  

For me the flow will not connect to my Fritz Box successfully.  

I am using user credentials created on the Fritzbox 7490 FRITZ!OS: 06.83, with System > Fritz!Box Users.  I allocate all rights to my user.

Is this the correct User Credentials?

**Comment by felixfischer** [comment]
Oliver, thank you for offering to take over. I am happy to accept.

What would you think is a good way to provide for a smooth transition?

**Comment by oliverlorenz** [comment]
Good question :sweat_smile: 

Maybe its a good way you give me additional to you, administration access to the repository. So I can the take over step by step. The other thing is npmjs.org which is more critical. We should be careful that we not break these dependency.

But maybe we should not discuss that in this issue. Feel free to mail when you're doing the first steps.  

`mail at oliverlorenz dot com` (english/german)

Greetings
Oliver

**Comment by oliverlorenz** [comment]
@mjunghanns

You're problem should be solved in version v2.0.0. Can you please have a look? If you have problems anyway please give me a hint here: https://github.com/oliverlorenz/node-red-contrib-fritzbox-presence :smile: :+1:
