### ISSUE TITLE
Node not visible in Node-Red Palette

### ISSUE THREAD

**Issue by nabbl** [felixfischer/node-red-contrib-fritzbox-presence#5]
Hi,

I installed this node succesfully on my node-red installation.
I use the raspberry pi image distributed by thethingbox.

Installing: **node-red-contrib-fritz** was working without problems.

But the presence node doesn't show up and I cannot see any errors in the logs when loading the palette.

Additional Infos:
thethingbox version: v2.4.2
Node-RED    version: v0.15.2
Node.js         version: v4.6.1

**Comment by felixfischer** [comment]
This repository is no longer maintained. Development is now taking place at [oliverlorenz/node-red-contrib-fritzbox-presence](https://github.com/oliverlorenz/node-red-contrib-fritzbox-presence).
